# Generated by Django 2.1.2 on 2019-02-11 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190211_1017'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='users',
        ),
    ]
